name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies and run lint
      working-directory: starter/backend
      run: |
        pip install pipenv flake8
        pipenv install
        pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies and run test
      working-directory: starter/backend
      run: |
        pip install pipenv
        pipenv install
        pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [linting, test]


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker, Check image and Run Docker
        working-directory: starter/backend
        run: |
          docker build --tag movie-pipeline-backend:latest .
          docker images|grep movie-pipeline-backend
          docker run -p 5000:5000 --name movie-pipeline-backend -d movie-pipeline-backend
      
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install
          pipenv run test

      