name: Backend CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY_BACKEND: ${{ secrets.ECR_REPOSITORY_BACKEND }}

jobs:
  build-and-deploy:
    name: Build and Push Backend Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show working directory and structure (debugging)
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la project/
          ls -la project/backend/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY_BACKEND:latest ./starter/backend
      
      - name: Tag Docker image
        run:
          docker tag $ECR_REPOSITORY_BACKEND:latest $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest
      
      - name: Push Docker image
        run:
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest
      
      - name: Deploy Docker Image to Amazon EKS
        working-directory: k8s
        run: |
          aws eks update-kubeconfig --name udacity-project4 --region us-east-1
          kustomize edit set image $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
          kustomize build | kubectl apply -f -