name: Deploy to ECR

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./starter/backend 

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_BACKEND }}

jobs:
  push-frontend:
    name: Push Frontend to ECR
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -R
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push Frontend Docker image
        run: 
          docker build -t $ECR_REPOSITORY:latest ./frontend
      - name: Tag Docker image
        run:
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Push Docker image
        run:
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  push-backend:
    name: Push Backend to ECR
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -R
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push Backend Docker image
        run:
          docker build -t $ECR_REPOSITORY:latest ./backend
      - name: Tag Docker image
        run:
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Push Docker image
        run:
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest