name: Deploy to ECR Frontend CD Pipeline

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY_FRONTEND: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
  CLUSTER_NAME: movie-pipeline-cluster

defaults:
  run:
    working-directory: ./starter/frontend

jobs:
  linting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code from repository
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.14'
            cache-dependency-path: package-lock.json

        - name: Cache NPM dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.OS }}-npm-cache-

        - name: Install NPM dependencies
          run: npm ci

        - name: Run lint
          run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run:  npm run test

  push-frontend:
    needs: [linting, test]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: List files
        run: ls -R

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, Tag and Push Frontend Docker image
        run: 
          docker build --build-arg REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest .

      - name: Push Docker image
        run:
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest

      - name: Configure kubeconfig
        run: 
            aws eks update-kubeconfig --name movie-pipeline-cluster --region us-east-1

      - name: Deploy to K8s
        run :   |
            cd k8s
            kustomize edit set image frontend=$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest
            kustomize build . | kubectl apply -f -
      
      - name: K8 info
        run :   |
            kubectl get svc -A